const products = [
    {
        id: 1,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 2,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 3,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 4,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 5,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 6,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 7,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 8,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 9,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 10,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {

        id: 11,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },
    {
        id: 1,
        brand: "Kraft Mac & Cheese",
        name: "Original Macaroni & Cheese Dinner",
        description: "There’s nothing quite like the original! Enjoy a bowl of comforting Kraft Mac and Cheese in under 10 minutes. Our signature, creamy Kraft cheese and enriched macaroni come together to make a delicious meal with no artificial flavors, dyes or preservatives. That’s something worth smiling about.",
        productType: "Product Type1",
        cheeseType: "Cheese Type1",
        shapes: "Shape1",
        mainImage: "p1.png",
        calories: 100,
        protein: 10,
        fat: 5,
        sugar: 2
    },

];